#################### Macros #####################

PROJ = colorlib

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O3
CDEFINES = -DBUILDING_COLORLIB

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS =
INCLUDE = include
SOURCE = src
TARGET = ../CatEyePC
OBJECTS = HSV \
          RGB
LIBNAME = colorlib

include $(TARGET)/makefiles/cpp_libs.mk