#################### Macros #####################

PROJ = bitmaps

# CC macros
COMMON_CFLAGS = -static-libgcc
CFLAGS = -O3
CDEFINES = -DBUILDING_LIBBITMAP

# CPP macros (additional to C macros)
COMMON_CPPFLAGS = -static-libstdc++
CPPFLAGS = 
CPPDEFINES =

# Universal macros
LIBS =
INCLUDE = include
SOURCE = src
TARGET = ../CatEyePC
OBJECTS = PreciseBitmap \
          PreviewBitmap
LIBNAME = bitmaps

include $(TARGET)/makefiles/cpp_libs.mk